### ISSUE TITLE
No AlbumTable provided

### ISSUE THREAD

**Issue by iamjonathankush** [jenzri-nizar/zf3-jquerydatatable#1]
There's no album table in the code which is used in the config.

**Comment by jenzri-nizar** [comment]
`
CREATE TABLE `album` (
  `id` int(11) NOT NULL,
  `artist` varchar(100) NOT NULL,
  `title` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

[album_sql.txt](https://github.com/jenzri-nizar/zf3-jquerydatatable/files/449080/album_sql.txt)
`

[Album.txt](https://github.com/jenzri-nizar/zf3-jquerydatatable/files/449071/Album.txt)
[AlbumTable.txt](https://github.com/jenzri-nizar/zf3-jquerydatatable/files/449072/AlbumTable.txt)
