### ISSUE TITLE
Not searching correctly

### ISSUE THREAD

**Issue by iamjonathankush** [jenzri-nizar/zf3-jquerydatatable#2]
@jenzri-nizar When I type in The Military Wives into the search box I get no responses.

**Comment by jenzri-nizar** [comment]
@iamjonathankush thank you to check your SQL query

**Comment by iamjonathankush** [comment]
@jenzri-nizar I'm not quite sure what that means. Something is wrong with your query. When I type The Military Wives into the application no results show but when i have nothing typed it shows

**Comment by iamjonathankush** [comment]
@jenzri-nizar Can you please tell me the code changes you make to these files for this bug so i can modify my version im not using composer

**Comment by iamjonathankush** [comment]
Your artist The Military Wives has two spaces between The and Military and Wives in the database so searches are coming up empty.
