### ISSUE TITLE
Cannot type in column search boxes

### ISSUE THREAD

**Issue by iamjonathankush** [jenzri-nizar/zf3-jquerydatatable#3]
@jenzri-nizar you cannot type in the column search boxes and have it filter. the only box that works is the search box

**Comment by jenzri-nizar** [comment]
thank you to check your SQL query

**Comment by iamjonathankush** [comment]
@jenzri-nizar I'm not quite sure what that means. You cannot type queries into the column search boxes

**Comment by iamjonathankush** [comment]
Yeh you were correct.
