### ISSUE TITLE
renderer causing issue with other renderers

### ISSUE THREAD

**Issue by iamjonathankush** [jenzri-nizar/zf3-jquerydatatable#5]
I lost my prior code so im recreating this again. this time, im using zf3. everything works except theres an issue using your code and the effects it apparently has on the Phprenderer object.

Here's my error. It's throwing an error on resolving the navigation code which means your code somehow did something. 

Here is the error code:

b>Fatal error</b>:  Zend\View\Exception\RuntimeException: Zend\View\Renderer\PhpRenderer::render: Unable to render template "navigation/navigation.phtml"; resolver could not resolve to a file in <b>/var/www/html/pp/vendor/zendframework/zend-view/src/Helper/Navigation/AbstractHelper.php</b> on line <b>153</b><br />

this error seems to result from the following code:

    private function Render(\Zend\View\Model\ViewModel $View){
        $renderer=new \Zend\View\Renderer\PhpRenderer();
        // i also tried using our global phprenderer with no success either
        //$renderer = Pluto::app()->getDesignHandler()->getPhprenderer();
        $renderer->setHelperPluginManager($this->getSm()->get('ViewRenderer')->getHelperPluginManager());        
        $resolver = new \Zend\View\Resolver\TemplateMapResolver([
            "DataTable"=> Pluto::path('module','Application/view/datatable/datatable.phtml')
        ]);
        $View->setTemplate("DataTable");
        $renderer->setResolver($resolver);
        return $renderer->render($View);
    }

Not quite sure how to resolve this. Thanks!

**Comment by iamjonathankush** [comment]
I think it has something to with the resolver and deleting my dependencies

**Comment by jenzri-nizar** [comment]
Check this function
 Pluto::path ( 'module', 'Application/view/datatable/datatable.phtml')
Because it must give shema absolute

**Comment by iamjonathankush** [comment]
No that function produces an absolute path to the datatable file whats happening is that its losing its stored pointers as you can see it no longer knows my navigation/navigation path

**Comment by iamjonathankush** [comment]
I resolved it the path wasnt on my tempate_map thanks

**Comment by iamjonathankush** [comment]
It seems to cause an error with this code in my layout.phtml file:

<?php echo $this->navigation('navigation')
                          ->menu()
                          ->setMinDepth(0)
                          ->setMaxDepth(0)
                          ->setUlClass('nav navbar-nav')
                          ->setPartial('navigation/navigation.phtml');
                ?>

For some reason my partial 'navigation/navigation.phtml' is no longer available from my layout template. 

I am using this somewhere else:

  return $this->getViewHelperPluginManager()->getRenderer();

This gets me the global renderer. so im using that elsewhere.

**Comment by jenzri-nizar** [comment]
Your file must be saved in that location
Layout/navigation/navigation.phtml
